### ISSUE TITLE
Reading Suomi24 vrt file in python3.7

### ISSUE THREAD

**Issue by ogencoglu** [CSCfi/Kielipankki-utilities#1]
Somehow lost here. How would I read a .VRT file (for example suomi24 corpus) into a dict, dataframe or anything structured in python? I would appreciate some pointers. Cheers!

**Comment by jpiitula** [comment]
I don't think we've got around to writing instructions on this. We're trying to be
rather strict with the format, so I would trust it and fix the data if there are any
surprises. Lines starting with a less-than sign are meta, others are data, and
usually consecutive data lines constitute a sentence; token lines are
tab-separated records.

Can you adapt the attached Python script for your purposes? I tested it
with some files that I had at hand, so it's not all wrong at least. (Sorry
about the file extension - a smart selection tool would not see a .py 
file at all.)

[reader.txt](https://github.com/CSCfi/Kielipankki-utilities/files/4404616/reader.txt)

**Comment by ogencoglu** [comment]
Kiitos! Thanks a lot! I will check this out.
